### PR TITLE
M0 query source features

### PR DESCRIPTION
**Pull request by Grodien**
This pull request adds querySourceFeature, getFilter and getLayerIds methods for Android, iOS and Web (getLayerIds not yet working)

### CODE REVIEW

**Comment by m0nac0** [comment]
Thank you for the contribution! I'll try to review this in the next days.

**Comment by m0nac0** [comment]
@Grodien Sorry for only getting back to this now. Does the example for querySourceFeature work for you on web? I always get an empty feature set (at least for vector tiles)

**Comment by Grodien** [comment]
@m0nac0 Just did some testing with our style and it seems querySourceFeature on vector tiles is not working on web. Its working fine with geojson sources.

**Comment by m0nac0** [comment]
@Grodien Thank you again for contributing/testing and your patience! I'll merge this now, having noted the restriction on web, since I haven't found out what causes these.

**Pull request merged**
