### PR TITLE
fix: fix the queryRenderedFeatures code on iOS

### PR DESCRIPTION
**Pull request by TimAlber**
There was a bug related to the queryRenderedFeatures code in the MapboxMapController.swift.
Now the mapView.visibleFeatures function is called with the correct parameters.

The android [RectF](https://developer.android.com/reference/android/graphics/RectF) structure uses bottom, left, right and top as parameter whereas the ios [CGRect](https://developer.apple.com/documentation/corefoundation/cgrect) structure uses x, y, width and height.

### CODE REVIEW

**Comment by m0nac0** [comment]
Good catch! There's already an example for queryRenderedFeatures at https://github.com/m0nac0/flutter-maplibre-gl/blob/a33ae7e694e5c776490410bdd1c980c7e98b99e6/example/lib/map_ui.dart#L347, so the new example page shouldn't be necessary.

**Comment by TimAlber** [comment]
I removed the example page.👍

**Comment by m0nac0** [comment]
@TimAlber I'm ready to merge this if you could merge current main into your branch (I don't have the necessary permissions to do it myself)

**Comment by m0nac0** [comment]
Thank you again for contributing!

**Pull request merged**
