### PR TITLE
Reenable textureMode which was disabled in f8b2d1

### PR DESCRIPTION
**Pull request by maxammann**
Similar to PR https://github.com/flutter-mapbox-gl/maps/pull/1216 which I found after doing a git bisect.

### CODE REVIEW

**Comment by mariusvn** [comment]
@m0nac0 can you take a look, looks like new android versions are incompatible with the current versions

**Comment by GaelleJoubert** [comment]
I tryed your fork, but I get the fllowing error : `E/FrameEvents( 1394): updateAcquireFence: Did not find frame.`

**Comment by m0nac0** [comment]
@maxammann Thank you for investigating this!

@GaelleJoubert Could you provide some more details about the error you are getting? Is the error only logged in the console or does the app crash/is the map not displayed etc.?

**Comment by m0nac0** [comment]
Since this is an important issue to fix, I'm merging this now. @GaelleJoubert Please let us know if you experience any serious issues with this PR.

**Comment by GaelleJoubert** [comment]
I'll try and let you know !

**Comment by GaelleJoubert** [comment]
Seems to work for me.
By the way, when adding a line layer with a geo json source, on android I have the issues :
` Drawable fr.kip.app:drawable/mapbox_user_icon_shadow has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).`
and
`{GLThread 228}[ParseStyle]: Layer 'LaBEkRJZ1D_0' has an invalid value for text-font and will not render text. Output values must be contained as literals within the expression.`

But, i don't see any visible issue other than the print on the log.

**Comment by m0nac0** [comment]
Ok good to hear. I'd say, if you experience any actual errors, open a new issue, if these are only printed to the log, ignore it for now. 
(It would be good of course to investigate these in more detail, but I doubt anyone currently has the capacity to do that if its not actually causing problems)

**Comment by GaelleJoubert** [comment]
Yeah, that's what I thought. No noticable issue for now, so no need to worry too much.
I just though i would mention these prints, in case they are relevent to someone.

**Pull request merged**
