### PR TITLE
feat: allow receiver to set the visibility of a layer

### PR DESCRIPTION
**Pull request by TimAlber**
Add a feature to let the receiver to set the visibility of a layer.

### CODE REVIEW

**Comment by m0nac0** [comment]
Thank you for contributing hits, I've actually implemented the same feature a few days ago in the `m0-toggle-vis` branch, we should compare if there are any advantages to either implementation.

**Comment by m0nac0** [comment]
Our implementations are very similar, differences are

- #138 also has a web implementation
- #138 has a smaller example, which I'd prefer since we already have a lot of example pages
- Your API accepts a list of layer ids, mine a single layer id. I don't have a strong opinion about this.

**Comment by TimAlber** [comment]
It is fine by me to use your implementation.
I will close my PR when yours is merged in.

**Comment by m0nac0** [comment]
Sorry about the duplication of effort ;)

**Comment by m0nac0** [comment]
Closing since this has been implemented in #138

**Pull request closed without merging**
