### PR TITLE
make necessary changes to update to agp 8.2.2

### PR DESCRIPTION
**Pull request by smallTrogdor**

### CODE REVIEW

**Comment by smallTrogdor** [comment]
https://github.com/maplibre/flutter-maplibre-gl/issues/310

**Comment by smallTrogdor** [comment]
Is there an estimate when this PR will be reviewed?

**Comment by m0nac0** [comment]
Thanks for contributing! Could you expand a little on the use case for this? That is, is there a specific reason you need to upgrade the AGP? (Not saying we shouldn't do it, I'm just trying to understand the use cases).

And do you know if this is still fully downward compatible, or could this e.g. cause issues when the app runs on old Android versions?

**Comment by m0nac0** [comment]
The CI is failing, because we explicitly install Java 11 so far, could you please change the version from 11 to 17 in` .github/workflows/flutter_ci.yml` line 54?

**Comment by smallTrogdor** [comment]
Dear @m0nac0 ,
thanks for reviewing! I will make the necessary changes today and commit the changes. As to your questions:

- The projects that I am working on depend / will depend on this package. As long as the AGP in this package is not upgraded, I will not be able to upgrade my projects / not be able to adopt it. I would not be able to profit from Gradle updates. _All people that use this package will have this issue, so the usage could drop in the future._
- ~~Gradle (and AGP) are generally _backwards_ compatible accross major versions. However, the dependent projects will have to update to gradle 8.
(please refer https://docs.gradle.org/current/userguide/feature_lifecycle.html#backwards_compatibility)~~
**EDIT**
- So, I made a mistake in my thinking. Sorry for the confusion! In general, the gradle version in this plugin will not affect the gradle version used to build the apps that use this plugin. Therefore, as long as this project does not use features that were removed / added in gradle 8 from previous versions (which it does not since I can build a project with gradle 7), there is no problem. The only thing that actually matters is the _namespace_ property in the android part of the gradle build file. This property is mandatory from gradle 8 up and will block other projects using gradle 8 and this plugin.

Thank you!

**Comment by smallTrogdor** [comment]
Please see EDIT on previous comment.

**Comment by m0nac0** [comment]
So if I understand correctly, we only really need to add the gradle `namespace` property (and maybe update the `group` property, if we are already at it) and delete the `package` attribute from the AndroidManifest, right? 
But we do not need to update Gradle, NDK and Java target versions in this plugin, since dependent projects could still use a newer Gradle version, right?

**Comment by m0nac0** [comment]
The flutter team seem to have used a conditional version of the namespace property to avoid breaking older projects: https://github.com/flutter/flutter/issues/125621#issuecomment-1525995461

**Comment by smallTrogdor** [comment]
Your are correct. There is two ways to deal with this:
Keep backwards compatible AGP until eternity (and build the switch like the flutter team) and never use any new features of Gradle ... 
Start upgrading the gradle version along with your releases plus ensure forward compatibility (I prefer it this way). Imo it does not make sense to retain backwards compatibility with AGP forever. As pointed out in the Issue you refered to:
_(Updating AGP may require other changes in your project as well, but over time using old versions of AGP is going to increasingly cause compatibility issues in general for projects, such as not being able to use current versions of some library dependencies, and not being able to use current versions of Android Studio, so is something anyone still using AGP 4.x should be seriously investigating regardless of this specific issue.) [here](https://github.com/flutter/flutter/issues/125621#issuecomment-1525500990)_

So you can choose option A or B and I will implement (maybe going from Gradle 4.x.x directly to 8 is a bit much) it accordingly (or you do it 😄 )

**Comment by smallTrogdor** [comment]
Hi @m0nac0,

can you give me an update on my previous question please ? Would like to close this PR and not have it hanging around forever ...

Thanks!

**Comment by smallTrogdor** [comment]
Hello @m0nac0,

any update??

**Comment by josxha** [comment]
Not the response that you are waiting for but in the meantime I'd like to join the conversation and share my feedback:
I like the choices that you made in this pull request. Sure, keeping backwards compatebility is nice to have, but the migration process started half a year ago, almost every maintained package is now migrated. Sadly, only maplibre_gl is one of the few packages that don't support gradle version 8 yet. Therefore I'm looking forward to when this package is up to date again. 

@smallTrogdor When testing your pull request, I needed to do some additional changes to get it to run. I don't really get why. Maybe because I'm using java 21? Do you have an idea?

In `android/build.gradle`:
```gradle
android {
  compileSdkVersion 34 // previously 31
  // ...
  compileOptions {
        sourceCompatibility JavaVersion.VERSION_19 // previously JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_19 // previously JavaVersion.VERSION_17
    }
```
And in `example/android/app/build.gradle`:
```gradle
android {
  // ...
  ndkVersion "25.1.8937393" // previously flutter.ndkVersion
```

Here is my flutter doctor output:
```console
[✓] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3447], locale de-DE)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
[✓] VS Code (version 1.88.1)
[✓] Connected device (3 available)
[✓] Network resources
```

**Comment by kuhnroyal** [comment]
I think we merged most of the changes from another PR, can you check what you think is still missing and open a new PR if required, thanks!

**Comment by smallTrogdor** [comment]
Hey @kuhnroyal ! So I saw all the good news and the story in #397 and I am really happy you are taking over. I am also thankful to @m0nac0 of course for all the past work - but it seems you are already putting a lot of work into this right now 👍 

I can make a subsequent PR for all the changes here (especially bump the example app) - will get to it next week!

**Pull request closed without merging**
