### PR TITLE
docs: add docusaurus

### PR DESCRIPTION
**Pull request by josxha**
This pull request 
- adds docusaurus as a solution for hosted documentation.
- cleans up the README.md
- adds the documentation and homepage field to the pubspec.yaml files

A preview can be viewed here: https://josxha.github.io/flutter-maplibre-gl/

### CODE REVIEW

**Comment by josxha** [comment]
Not sure how to fix the dependency review CI.
```console
Error: $GITHUB_STEP_SUMMARY upload aborted, supports content up to a size of 1024k, got 1975k.
```
The markdown summary exceeds the maximum size. Maybe because docusaurus adds too many dependencies at once?

**Review by Zverik — APPROVED** [review]
This looks great! I'm not sure if keeping all the docs for every version is a proper way to go, but why not. From the instructions, it is also not clear how to edit docs for an earlier version, for example.

**Comment by josxha** [comment]
> I'm not sure if keeping all the docs for every version is a proper way to go, but why not.

This way it's possible to edited or improve old documentation as well as edit the latest version. 

> From the instructions, it is also not clear how to edit docs for an earlier version, for example.

Not sure how much documentation should get copied over from the docusaurus docs. They have documentaiton about versioned docs at https://docusaurus.io/docs/versioning. For users that just want to fix a typo or similar there is always the "Edit this page" button on every docs page.

**Comment by josxha** [comment]
I'm using this documentation page on the new [maplibre](https://github.com/josxha/flutter-maplibre) package but if wanted we can still include it into this project, too.

**Comment by josxha** [comment]
Some additional notes: maplibre-gl-js had a discussion about the "right" static site generator in https://github.com/maplibre/maplibre-gl-js/issues/2150. In the end it's probably comes down to personal preference. I decided to go with docusaurus when creating this pr because of some features like versioned docs, an awesome site search and so on. As all documentation is in markdown, it would be possible to go with an other site generator, too.

The scope of this pull request is to provide a basic documentation setup. Adding full documentation is out of scope.

Because many npm dependencies are added in this pr, the Dependency Review CI fails.

**Comment by josxha** [comment]
Closing off this pull request now...

**Pull request closed without merging**
