### PR TITLE
chore(example): responsive design

### PR DESCRIPTION
**Pull request by josxha**
- responsive design ~~for main page~~
- link to pub.dev and github from the main page
- update icons
- delete unused example/READEME.md file

### CODE REVIEW

**Review by kuhnroyal — APPROVED** [review]
Nice work!
The sample crashes on my iOS simulator, same for you?
This is unrelated to this PR tho.

**Comment by josxha** [comment]
Thanks for the review!
I can't test on the iOS Simulator because i don't have a up-to-date mac but I it doesn't crash for me when running on appetize.io (an iOS emulator on the web). Could it be that your problem is related to https://github.com/maplibre/flutter-maplibre-gl/issues/388?

I'd like to do more work on the example app, mostly making it completely responsive. Do you prefer it in multiple pull requests or would one bigger pr be fine for you?

**Comment by kuhnroyal** [comment]
I don't mind bigger PRs for the example app :)
That issues you linked is probably the reason, thanks.

**Comment by josxha** [comment]
@kuhnroyal this pull request got big quick 😅 I changed the example app to use `Wrap`s for it's buttons and expanded the map widget for a better experience on large screens. Additionally I moved the buttons to the top to reduce the distance between them and the back button. Still no award-winning layout, but hopefully an improvement. No functionality *should* have been touched. Let me know if you want anything to get changed.

**Comment by josxha** [comment]
ngx-maplibre-gl has a great showcase: https://maplibre.org/ngx-maplibre-gl/demo/display-map
Maybe we can do something similar in the future?

**Comment by josxha** [comment]
Closing because the pull request was done before repository got restructued. It might take less time to start fresh on the current code base.

**Pull request closed without merging**
