### PR TITLE
Trimming styleString to simplify the JSON detection

### PR DESCRIPTION
**Pull request by mariusvn**
I trim the styleString to allow spaces at the start of json strings

### CODE REVIEW

**Comment by thertzelle** [comment]
What about iOS?

**Comment by mariusvn** [comment]
that's true, I need to add it to IOS, my bad

**Comment by mariusvn** [comment]
I took a look at IOS and it looks like the json style without URL is currently not supported so i won't do it here. I don't know swift at all so if i work on it i'll break everything 😅.

**Review by m0nac0 — APPROVED** [review]
Sorry for taking so long, but thank you for your contribution!

**Pull request merged**
