### PR TITLE
feat!: use lower camel case for enum fields and consts

### PR DESCRIPTION
**Pull request by josxha**
Lower camel case is the preferred naming convention for constants and enum fields.
This pull request is breaking.

### CODE REVIEW

**Comment by kuhnroyal** [comment]
This can go into a `0.20.0` release. Is there a lint that we can enable for this?

**Comment by josxha** [comment]
> Is there a lint that we can enable for this?

It might be possible to create decrecations for the old enum fields. Would require some temporary code though.

**Comment by kuhnroyal** [comment]
I think thats overkill but the disabled lint in analysis_options ca be enabled with this change?

**Comment by josxha** [comment]
Ohh you're right, totally forgot about that!
Update: fixed

**Review by kuhnroyal — APPROVED** [review]

**Pull request merged**
